In [1]:
#1. buat matrix X berukuran 2x3 menggunakan numpy

import numpy as np

X = np.array([[3, 4, 2], [3, 9, 7]])
X

array([[3, 4, 2],
       [3, 9, 7]])

In [ ]:
#tampilkan ukuran dari matrix X
X.shape

In [ ]:
#tampilkan seluruh elemen dari kolom pertama dari matrix X

X[:,0]

In [ ]:
#tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:]

Pytorch

In [3]:
#2. buat matrix X berukuran 2x3 menggunakan PyTorch

import torch

X_pt = torch.tensor([[14, 12, 9], [10, 15, 18]])
X_pt

tensor([[14, 12,  9],
        [10, 15, 18]])

In [4]:
#tampilkan ukuran dari matrix X

X_pt.shape

torch.Size([2, 3])

In [ ]:
#tampilkan seluruh elemen dari kolom pertama dari matrix X

X_pt[:,0]

In [ ]:
#tampilkan seluruh elemen dari baris kedua dari matrix X

X_pt[1,:]

Tensorflow

In [5]:
#buat matrix X berukuran 2x3 menggunakan Transflow

import tensorflow as tf

X_tf = tf.Variable([[17, 20, 24], [31, 22, 26]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[17, 20, 24],
       [31, 22, 26]], dtype=int32)>

In [ ]:
#tampilkan ukuran dari matrix X

tf.shape(X_tf)

In [ ]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X

X_tf[:,0]


In [ ]:
#tampilkan seluruh elemen dari baris kedua dari matrix X

X_tf[1,:]