In [22]:
#1.  buat vector x dengan ukuran 3x1

import numpy as  np
x = np.array([[20],
              [35],
              [45]])
print(f"menampilkan vector x:  \n{x}")

menampilkan vector x:  
[[20]
 [35]
 [45]]


In [11]:
#hitung panjang vector x

print(f"panjang vektor x adalah: {len(x)}")

panjang vektor x adalah: 3


In [13]:
#tampilkan ukuran vector x

print(f"ukuran dar vector x adalah: {x.shape}")

ukuran dar vector x adalah: (3, 1)


In [16]:
#tampilkan tipe data dari vector x

print(f"tipe data dari vector x adalah: {type(x)}")


tipe data dari vector x adalah: <class 'numpy.ndarray'>


In [17]:
# akses elemen pertama dari vector x

print(f"elemen pertama dari vector x adalah: {x[0]}")

elemen pertama dari vector x adalah: [20]


In [27]:
##tampilkan tipe data elemen pertama dari vector x

print(f"tipe data semua elemen adalah: {type(x[0,0])}")

tipe data semua elemen adalah: <class 'numpy.int64'>


2. Soal nomor 2

In [28]:
#2. lakukan transpose pada vector x dan simpan pada variabel x_t

x_t = x.T
print(f"hasil transpose x: {x_t}")

hasil transpose x: [[20 35 45]]


In [30]:
# tampilkan ukuran dari vector x_t

print(f"ukuran dari vector x_t adalah: {x_t.shape}")

ukuran dari vector x_t adalah: (1, 3)


In [40]:
# lakukan transpose pada vector y dan simpan pada variabel y_t

y = np.array([[21, 30, 45]])
print(f"vector y adalah: {y}")

y_t = y.T
print(f"hasil transpose y: \n{y_t}")

vector y adalah: [[21 30 45]]
hasil transpose y: 
[[21]
 [30]
 [45]]


In [42]:
# tampilkan ukuran dari vector x_t

print(f"ukuran dari vector y_t adalah: {y_t.shape}")

ukuran dari vector y_t adalah: (3, 1)


3.  lakukan soal nomor 2 menggunakan pytorch dan tensorflow

PyTorch

In [53]:
import torch


#lakukan transpose pada vector x dan simpan pada variabel x_t

x_pt = torch.tensor(x)
x_pt_t = x_pt.T
print(f"hasil transpose x: {x_pt_t}")


hasil transpose x: tensor([[20, 35, 45]])


In [51]:
# tampilkan ukuran dari vector x_t

print(f"ukuran dari vector x adalah: {x_pt_t.shape}")


ukuran dari vector x adalah: torch.Size([1, 3])


In [52]:
# lakukan transpose pada vector y dan simpan pada variabel y_t

y_pt = torch.tensor(y)
y_pt_t = y_pt.T
print(f"hasil transpose y: \n{y_pt_t}")

hasil transpose y: 
tensor([[21],
        [30],
        [45]])


In [54]:
# tampilkan ukuran dari vector x_t

print(f"ukuran dari vector  x adalah: {x_pt_t.shape}")

ukuran dari vector  x adalah: torch.Size([1, 3])


TensorFlow

In [58]:
import tensorflow as tf

#lakukan transpose pada vector x dan simpan pada variabel x_t

x_tf = tf.transpose(x)
print(f"hasil dari transpose x: {x_tf}")

hasil dari transpose x: [[20 35 45]]


In [59]:
#tampilkan ukuran dari vector x_tf

print(f"ukuran dari vector x_tf adalah: {x_tf.shape}")

ukuran dari vector x_tf adalah: (1, 3)


In [61]:
# lakukan transpose pada vector y dan simpan pada variabel y_t

y_tf = tf.transpose(y)
print(f"hasil dari transpose y_tf : \n{y_tf}")

hasil dari transpose y_tf : 
[[21]
 [30]
 [45]]


In [63]:
#tampilkan ukuran dari vector x_t

print(f"ukuran dari vector x_tf adalah: {x_tf.shape}")

ukuran dari vector x_tf adalah: (1, 3)
