In [11]:
import numpy as np
import torch
import tensorflow as tf

In [6]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy

X = np.array([[1, 2, 3], [4, 5, 6]])
X
print(f"menampilkan matrix x: \n{X}")

menampilkan matrix x: 
[[1 2 3]
 [4 5 6]]


In [16]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = torch.tensor([[1, 2, 3], [4, 5, 6]])
X_pt
print(f"menampilkan matrix x_pt: \n{X_pt}")

menampilkan matrix x_pt: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [12]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[1, 2, 3], [4, 5, 6]])
X_tf
print(f"menampilkan matrix x_tf: \n{X_tf}")

menampilkan matrix x_tf: 
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>


In [8]:
# lakukan perkalian matrix X, X_pt dan X_tf dengan suatu skalar
#X

print(f"hasil perkalian dari matrix adalah")
print(X*2)

hasil perkalian dari matrix adalah
[[ 2  4  6]
 [ 8 10 12]]


In [17]:
X_pt
print(f"hasil perkalian dari matrix adalah")
print(X_pt*2)

hasil perkalian dari matrix adalah
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


In [18]:
#X_tf
print(f"hasil perkalian dari matrix adalah")
print(X_tf*2)

hasil perkalian dari matrix adalah
tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [19]:
# lakukan penjumlahan matrix x, x_pt dan X_tf dengan suatu skalar
#X
print(f"hasil penjumlahan dari matrix adalah")
print(X+2)

hasil penjumlahan dari matrix adalah
[[3 4 5]
 [6 7 8]]


In [ ]:
#X_pt
print(f"hasil penjumlahan dari matrix adalah")
print(X_pt+2)

In [ ]:
#X_tf
print(f"hasil penjumlahan dari matrix adalah")
print(X_tf+2)

In [ ]:
# lakukan pengurangan matrix X, X_pt dan X_tf dengan suatu skalar
#X

print(f"hasil pengurangan dari matrix adalah")
print(X-2)

In [ ]:
#X_pt
print(f"hasil pengurangan dari matrix adalah")
print(X_pt-2)

In [21]:
#X_tf

print(f"hasil pengurangan dari matrix adalah")
print(X_tf-2)

hasil pengurangan dari matrix adalah
tf.Tensor(
[[-1  0  1]
 [ 2  3  4]], shape=(2, 3), dtype=int32)


2

In [20]:
# buat matrix y dengan ukuran 2x3 menggunakan numpy
y = np.array ([[1, 2, 3], [4, 5, 6]])
print(f"menampilkan matrix y: \n{y}")

menampilkan matrix y: 
[[1 2 3]
 [4 5 6]]


In [24]:
# buat matrix Y_pt dengan ukuran 2x3 menggunakan pytorch
Y_pt = torch.tensor([[1, 2, 3], [4, 5, 6]])
Y_pt
print(f"menampilkan matrix y: \n{y}")

menampilkan matrix y: 
[[1 2 3]
 [4 5 6]]


In [28]:
# buat matrix y_tf dengan ukuran 2x3 menggunakan tensorflow

Y_tf = tf.Variable([[1, 2, 3], [4, 5, 6]])
print(f"menampilkan matriks y)tf : {Y_tf}")

menampilkan matriks y)tf : <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>


In [22]:
# kalikan matrix X dengan Y
print(f"hasil matrix x dengan y adalah")
X*y

hasil matrix x dengan y adalah


array([[ 1,  4,  9],
       [16, 25, 36]])

In [30]:
# kalikan matrix X_pt dengan Y_pt
print(f"hasil matrix x_pt dengan y_pt adalah")
X_pt * Y_pt

hasil matrix x_pt dengan y_pt adalah


tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [29]:
# kalikan matrix X_tf dengan Y_tf
print(f"hasil matrix x_tf dengan y_tf adalah")
X_tf * Y_tf

hasil matrix x_tf dengan y_tf adalah


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>