In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
# buat matrix dengan ukuran 2x3 menggunakan numpy
X = np.array([[1, 2, 3], [4, 5, 6]])
X
print(f"matrix x adalah: \n{x}")

matrix x adalah: 
[[1 2 3]
 [4 5 6]]


In [18]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = torch.tensor([[1, 2, 3], [4, 5, 6]])
X_pt
print(f"matrix x_pt adalah: \n{X_pt}")

matrix x_pt adalah: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [10]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf. Variable([[[1, 2, 3], [4, 5, 6]]])
X_tf
print(f"matrix x_tf adalah: \n{X_tf}")

matrix x_tf adalah: 
<tf.Variable 'Variable:0' shape=(1, 2, 3) dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>


In [19]:
# lakukan transpose pada matrix x, x_pt dan x_tf
#numpy

X = x.T
print(f"hasil transpose dari matrix x adalah: \n{x}")

hasil transpose dari matrix x adalah: 
[[1 2 3]
 [4 5 6]]


In [20]:
#Pytorch

X_pt = X_pt.T
print(f"hasil transpose dari matrix x_pt adalah: \n{X_pt}")

hasil transpose dari matrix x_pt adalah: 
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [24]:
#Tensorflow

X_tf = tf.transpose(X_tf)
print(f"hasil transpose dari matrix X_tf adalah: \n{X_tf}")

hasil transpose dari matrix X_tf adalah: 
[[[1]
  [4]]

 [[2]
  [5]]

 [[3]
  [6]]]
