In [1]:
#Import Library
import numpy as np
import torch
import tensorflow as tf

In [4]:
# 1. Membuat vector 1x3
# NumPy
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(f"x: {x}")
print(f"y: {y}")

# PyTorch
x_pt = torch.tensor([1, 2, 3])
y_pt = torch.tensor([4, 5, 6])

print(f"x_pt: {x_pt}")
print(f"y_pt: {y_pt}")

# TensorFlow
x_tf = tf.Variable([1, 2, 3])
y_tf = tf.Variable([4, 5, 6])

print(f"x_tf: {x_tf}")
print(f"y_tf: {y_tf}")


x: [1 2 3]
y: [4 5 6]
x_pt: tensor([1, 2, 3])
y_pt: tensor([4, 5, 6])
x_tf: <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
y_tf: <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 5, 6], dtype=int32)>


In [ ]:
# 2. Dot Product
# NumPy
print("NumPy dot:", np.dot(x, y))
# PyTorch
print("PyTorch dot:", torch.dot(x_pt, y_pt))
# TensorFlow
print("TensorFlow dot:", tf.tensordot(x_tf, y_tf, axes=1))

NumPy dot: 32
PyTorch dot: tensor(32)
TensorFlow dot: tf.Tensor(32, shape=(), dtype=int32)


In [8]:
#lakukan perhitungan excercise menggunakan collab
#1
Y = np.array([[42, 4, 7, 99], [-99, -3, 12, 22]])
print(f"tampilkan \n{Y}")

#y transpose
Y_t = Y.T
print(f"hasil tranpose matriks Y adalah: \n{Y_t}")

tampilkan 
[[ 42   4   7  99]
 [-99  -3  12  22]]
hasil tranpose matriks Y adalah: 
[[ 42 -99]
 [  4  -3]
 [  7  12]
 [ 99  22]]


In [14]:
#2

A = np.array([[25, 10], [-2 , 1]])
B = np.array([[-1, 7], [10,  8]])
print(f"tampilkan \n{A}")
print(f"tampilkan \n{B}")

#hadddamart

result = A * B
print(f"hasil perkalian haddamard matriks diatas adalah: \n{result}")

tampilkan 
[[25 10]
 [-2  1]]
tampilkan 
[[-1  7]
 [10  8]]
hasil perkalian haddamard matriks diatas adalah: 
[[-25  70]
 [-20   8]]


In [18]:
#3

w = np.array([-1, 2, -2])
x = np.array([5, 10, 0])
print(f"tampilkan w: {w}")
print(f"tampilkan x: {x}")

#dot product
result = np.dot(w, x)
print(f"hasil dot product matriks diatas adalah: {result}")

tampilkan w: [-1  2 -2]
tampilkan x: [ 5 10  0]
hasil dot product matriks diatas adalah: 15
