untuk no 1. 2. 3.

numpy

In [1]:
import numpy as np

In [41]:
#1. buat matrix A dengan ukuran 2x3 dan vector b berukuran 3x1 menggunakan numpy
A = np.array([[4, 3, 4], [4, 5, 7]])
print(f"Matrix A adalah: \n{A}")


Matrix A adalah: 
[[4 3 4]
 [4 5 7]]


(2, 3)

In [3]:
#vector 3x1
b = np.array([[9], [4], [5]])
print(f"Vector b adalah: \n{b}")

Vector b adalah: 
[[9]
 [4]
 [5]]


In [43]:
#t2. ampilkan ukuran matrix A dan vector b

print(f"Ukuan matrix A adalah: {A.shape}")
print(f"Ukuran vector b adalah: {b.shape}")

Ukuan matrix A adalah: (2, 3)
Ukuran vector b adalah: (3, 1)


In [19]:
#3. kalikan matrix A dengan vector b
print(f"hasil perkalian matriks A dan vector b adalah: \n{np.dot(A, b)}")

hasil perkalian matriks A dan vector b adalah: 
[[68]
 [91]]


pytorch

In [6]:
import torch

In [9]:
#1. buat matrix A_pt dengan ukuran 2x3 dan vector b_pt berukuran 3x1 menggunakan pytorch
A_pt = torch.tensor([[1, 5, 8], [4, 6, 4]])
print(f"Matrix A_pt adalah: \n{A_pt}")


Matrix A_pt adalah: 
tensor([[1, 5, 8],
        [4, 6, 4]])


In [10]:
#vector 3x1
b_pt = torch.tensor([[4], [3], [7]])
b_pt

tensor([[4],
        [3],
        [7]])

In [21]:
#3. kalikan matrix A_pt dengan vector b_pt
print(f"hasil perkalian matrix A_pt dengan vector b_pt adalah: \n{torch.matmul(A_pt, b_pt)}")

hasil perkalian matrix A_pt dengan vector b_pt adalah: 
tensor([[75],
        [62]])


tensorflow

In [11]:
import tensorflow as tf

In [15]:
#1. buat matrix A_tf dengan ukuran 2x3 dan vector b_tf berukuran 3x1 menggunakan tensorflow
A_tf = tf.Variable([[1, 5, 7], [4, 6, 9]])
print(f"Matrix A_tf adalah: \n{A_tf}")

Matrix A_tf adalah: 
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 5, 7],
       [4, 6, 9]], dtype=int32)>


In [14]:
#vector 3x1
b_tf = tf.Variable([[7], [8], [5]])
print(f"Vector b_tf adalah: \n{b_tf}")

Vector b_tf adalah: 
<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[7],
       [8],
       [5]], dtype=int32)>


In [23]:
#3. kalikan matrix A_tf dengan vector b_tf
print(f"hasil perkalian matrix A_tf dgn vector b_tf adalah: \n{tf.linalg.matmul(A_tf, b_tf)}")

hasil perkalian matrix A_tf dgn vector b_tf adalah: 
[[ 82]
 [121]]


-------------------------------------------------------

untuk no 4. 5.

numpy

In [24]:
#4. buat matrix B dengan ukuran 3x3 menggunakan numpy
B = np.array([[3, 3, 9], [2, 6, 7], [3, 4, 8]])
print(f"Matrix B adalah: \n{B}")

Matrix B adalah: 
[[3 3 9]
 [2 6 7]
 [3 4 8]]


In [28]:
#5. kalikan matrix A dengan matrix B
print(f"Hasil perkalian A dengan Matrix B adalah: \n{np.dot(A, B)}")

Hasil perkalian A dengan Matrix B adalah: [[ 30  46  89]
 [ 43  70 127]]


pytorch

In [25]:
#4. buat matrix B_pt dengan ukuran 3x3 menggunakan pytorch
B_pt = torch.tensor([[4, 5, 9], [1, 9, 4], [3, 4, 6]])
print(f"Matrix B_pt adalah: \n{B_pt}")

Matrix B_pt adalah: 
tensor([[4, 5, 9],
        [1, 9, 4],
        [3, 4, 6]])


In [30]:
#5. kalikan matrix A_pt dengan matrix B_pt
print(f"hasil perkalian matrix A_pt dengan matrix B_pt adalah: \n{torch.matmul(A_pt, B_pt)}")

hasil perkalian matrix A_pt dengan matrix B_pt adalah: 
tensor([[33, 82, 77],
        [34, 90, 84]])


tensorflow

In [27]:
#4. buat matrix B_tf dengan ukuran 3x3 menggunakan tensorflow
B_tf = tf.Variable([[5, 8, 7], [1, 4, 9],[3, 4, 9]])
print(f"Matrix B_tf adalah: \n{B_tf}")

Matrix B_tf adalah: 
<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[5, 8, 7],
       [1, 4, 9],
       [3, 4, 9]], dtype=int32)>


In [32]:
#5. kalikan matrix A_tf dengan matrix B_tf
print(f"hasil perkalian matrix A_tf dengan matrix B_tf adalah: \n{tf.linalg.matmul(A_tf, B_tf)}")

hasil perkalian matrix A_tf dengan matrix B_tf adalah: 
[[ 31  56 115]
 [ 53  92 163]]


no 6.

Buktikan apakah perkalian matrix bersifat kumutatif?

In [42]:
#6. buktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?
#numpy
#perkalian AXB

print(f"hasil perkalian A dengan B adalah: \n{np.dot(A, B)}")

#BXA
print(f"hasil perkalian B dengan A adalah: \n{np.dot(B, A)}")

#maka dapat disimpulkan bahwa perkalian matrix tidak bersifat komutatif. AXB tidak sama dengan BXA


hasil perkalian A dengan B adalah: 
[[ 30  46  89]
 [ 43  70 127]]


ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)