Perhitungan soal excercise

excercise ppt bapak

In [ ]:
import torch

In [ ]:
#1
A_pt = torch.tensor([[0, 1, 2],
                  [3, 4, 5],
                  [6, 7, 8]])

v_pt = torch.tensor([[-1],
                  [1],
                  [-2]])

result = torch.matmul(A_pt, v_pt)
print(f"hasil nomor 1 adalah: \n{result}")


hasil nomor 1 adalah: 
tensor([[ -3],
        [ -9],
        [-15]])


In [ ]:
I = torch.eye(3)
print(f"I adalah: \n{I}")

result2 = torch.matmul(I, v_pt.float())
print(f"hasil nomor 2 adalah: \n{result2}")

I adalah: 
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
hasil nomor 2 adalah: 
tensor([[-1.],
        [ 1.],
        [-2.]])


In [ ]:
#3

B_pt = torch.tensor([[-1, 0], [1, 1], [-2, 2]])
print(f"matriks B: \n{B_pt}")

result3 = torch.matmul(A_pt, B_pt)
print(f"hasil dari perkalian matriks A dan B adalah: \n{result3}")

matriks B: 
tensor([[-1,  0],
        [ 1,  1],
        [-2,  2]])
hasil dari perkalian matriks A dan B adalah: 
tensor([[ -3,   5],
        [ -9,  14],
        [-15,  23]])
