Matrix Inversion

numpy

In [ ]:
import numpy as np

In [ ]:
#buat matrix X ukuran 2x2 menggunakan numpy
X = np.array([[4, 2], [-5, -3]])
print(f"Matriks  X adalah: \n{X}")

Matriks  X adalah: 
[[ 4  2]
 [-5 -3]]


In [ ]:
#buat invers dari matrix X dan beri nama Xinv menggunakan numpy
Xinv = np.linalg.inv(X)
print(f"Invers matriks X adalah: \n{Xinv}")

Invers matriks X adalah: 
[[ 1.5  1. ]
 [-2.5 -2. ]]


In [ ]:
#kalikan X dengan Xinv menggunakan numpy
print(f"hasil perkalian adalah: \n{np.dot(Xinv, X)}")

hasil perkalian adalah: 
[[1.00000000e+00 3.33066907e-16]
 [0.00000000e+00 1.00000000e+00]]


selesaikan persamaan berikut menggunakan numpy, tensorflow dan pytorch

4b + 2x = 4

-5b - 3 = -7

In [ ]:
X = np.array([[4, 2], [-5, -3]])
print(f"Tampilkan: \n{X}")

Tampilkan: 
[[ 4  2]
 [-5 -3]]


In [ ]:
V = ([4, -7])
print(f"Tampilkan: \n{V}")

Tampilkan: 
[4, -7]


In [ ]:
C =  np.linalg.solve(X, V)
print(f"Hasil: \n{C}")

Hasil: 
[-1.  4.]


torch dan tensorflow

In [ ]:
import torch
import tensorflow as tf


In [ ]:
#torch
X_pt = torch.tensor([[4, 2], [-5, -3]])
print(f"Matriks X: \n{X_pt}")

Matriks X: 
tensor([[ 4,  2],
        [-5, -3]])


In [ ]:
V_pt  = torch.tensor([4, -7])
print(f"Vektor V: \n{V_pt}")

Vektor V: 
tensor([ 4, -7])


In [ ]:
C_pt  = torch.linalg.solve(X_pt.float(), V_pt.float())
print(f"Hasil: \n{C_pt}")

Hasil: 
tensor([-1.,  4.])


In [ ]:
#tensorflow

X_tf = tf.Variable([[4., 2.], [-5., -3.]])
print(f"Matriks X: \n{X_tf}")

Matriks X: 
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 4.,  2.],
       [-5., -3.]], dtype=float32)>


In [ ]:
V_tf = tf.Variable([[4.],[7.]])
print(f"Vektor V: \n{V_tf}")

Vektor V: 
<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[4.],
       [7.]], dtype=float32)>


In [ ]:
C_tf = tf.linalg.solve(X_tf, V_tf)
print(f"Hasil: \n{C_tf}")

Hasil: 
[[ 12.999997]
 [-23.999996]]
