In [ ]:
import numpy as np

In [ ]:
# buatlah matriks simetris dengan ukuran 3x3 dan buktikan bahwa itu merupakan matriks simetris
print(f"menampilkan matriks simetris ukuran 3x3 sebagai berikut:")
X_sym = np.array([[0, 1, 2], [1, 7, 8], [2, 8, 9]])
X_sym

menampilkan matriks simetris ukuran 3x3 sebagai berikut:


array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [ ]:
print(f"hasil pembuktian dari matriks simetris sebagai berikut:")
X_sym.T == X_sym

hasil pembuktian dari matriks simetris sebagai berikut:


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
import torch

In [ ]:
# menggunakan pytorch, buatlah matriks identitas I dengan ukuran 4x4
print(f"menampilkan matriks identitas dengan ukuran 4x4 sebagai berikut:")
I = torch.tensor([[1, 0, 0, 0],
                  [0, 1, 0, 0],
                  [0, 0, 1, 0],
                  [0, 0, 0, 1]])
I

menampilkan matriks identitas dengan ukuran 4x4 sebagai berikut:


tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

In [ ]:
# menggunakan pytorch, buatlah vector b_pt dengan ukuran 4x1
print(f"menampilkan vector b_pt dengan ukuran 4x1 sebagai berikut:")
b_pt = torch.tensor([[1],
                     [2],
                     [3],
                     [4]])
b_pt

menampilkan vector b_pt dengan ukuran 4x1 sebagai berikut:


tensor([[1],
        [2],
        [3],
        [4]])

In [ ]:
# kalikan matrix I dengan vector b_pt
print(f"hasil dari matrix I dengan vektor b_pt adalah:")
I*b_pt

hasil dari matrix I dengan vektor b_pt adalah:


tensor([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]])